### ISSUE TITLE
library not found for -lWorklightStaticLibProject

### ISSUE THREAD

**Issue by rondayu** [IdanAdar/Using-Storyboard#1]
hi Idan, do you know why Xcode print the error which say "library not found for -lWorklightStaticLibProject" when I run worklight6.2 project in Xcode7beta. Do you know how to solve it?

**Comment by IdanAdar** [comment]
This project was built with Xcode 6.2; I suspect things have changed since then...

**Comment by rondayu** [comment]
hi Idan, in my case , we just update my project to worklight6.2, do you know how to deal with lWorklightStaticLibProject library missing case?

**Comment by rondayu** [comment]
hi Idan, I found out it's just missing that library. and problems solve after add new one to the Xcode project.
